function AddTextEntry(key, value)
Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
-- ONX Emergency Vehicle Wheels
-- Sedans (Muscle)
AddTextEntry('wheelonxpol_musc_01','Vapid Steelie Lug Cover')
AddTextEntry('wheelonxpol_musc_02','Service Steelie')
AddTextEntry('wheelonxpol_musc_03','Vapid Steelie Dodger Hub')
AddTextEntry('wheelonxpol_musc_04','Vapid Plastic Trim Cover')
AddTextEntry('wheelonxpol_musc_05','Vapid Chrome Trim Cover')
AddTextEntry('wheelonxpol_musc_06','Declasse 9D1 Steelie')
AddTextEntry('wheelonxpol_musc_07','Declasse 8D1 Steelie')
AddTextEntry('wheelonxpol_musc_08','Bravado AWD5 ')
AddTextEntry('wheelonxpol_musc_09','Declasse 7D1 Steelie ')
-- SUVs
AddTextEntry('wheelonxpol_suv_01','Vapid AWD Utility 65S')
AddTextEntry('wheelonxpol_suv_02','Declasse AWD Utility Six Post')
AddTextEntry('wheelonxpol_suv_03','Vapid 4WD Utility Columbus')
AddTextEntry('wheelonxpol_suv_04','Canis 4WD Utility Steelie')
AddTextEntry('wheelonxpol_suv_04','Bravado Six Spoke Utility')
AddTextEntry('wheelscoutc_suv_01','Scout 94 Steelie Chrome')
AddTextEntry('wheelscoutc_suv_02','Scout 94 Steelie')
AddTextEntry('wheelscoutc_suv_03','Scout 94 Stock Paint')
AddTextEntry('wheelscoutc_suv_04','Scout 94 Stock Brushed')
AddTextEntry('wheeltfbison_suv_01','Bravado Pickup Utility')
AddTextEntry('wheeltfbison_suv_02','Bravado Spangled 6 Chrome')
AddTextEntry('wheeltfbison_suv_03','Bravado Spangled 6')
-- OffRoad
AddTextEntry('WHEELSAND_OFF_01', 'Hellenbach')
AddTextEntry('WHEELSAND_OFF_02', 'Sandstorm Chrome')
AddTextEntry('WHEELSAND_OFF_03', 'Sandstorm Duty')
AddTextEntry('WHEELSAND_OFF_04', 'Sandstorm Deluxe')
AddTextEntry('WHEELSAND_OFF_05', 'Sandstorm Vigour')
AddTextEntry('WHEELSAND_OFF_06', 'Sandstorm Vigour Off-Road')
AddTextEntry('wheelscoutc_off_01','Scout 94 Steelie Chrome')
AddTextEntry('wheelscoutc_off_02','Scout 94 Steelie')
AddTextEntry('WHEELTFBISON_OFF_01','Bison Platinum')
end)